services:
  - type: web
    name: xrp-whales-bot
    env: python
    plan: free
    pythonVersion: 3.12.1  # <- versiÃ³n estable compatible
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python xrp_whales_bot.py




